[mod]
name = "test-finder"
version = "0.1.0"
external_elements = [
    {path = "mods/loader_test/test_element.toml", name = "test_element"},
]

# Completely arbitrary
incompatible_mods = [
    "mods/nousersthings.js",
    "mods/lightmap.js",
    "mods/betterSettings.js"
]

[scripts]
preload  = [
    "mods/loader_test/pre_load.js",
    "mods/loader_test/random_file.js"
]
postload = [
    "mods/loader_test/post_load.js",
    "mods/loader_test/random_file.js"
]